title: First steps in Choco-solver
description: >-
  In this course, we will discover the basic building blocks to model and solve
  a problem with the Choco-solver library. 
template:
  repo: first-steps-in-choco-solver-template
  name: first-steps-in-choco-solver
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
